"""
Shared paths for the test suite.

The published pages moved once -- /app/ became /form/, and /disclaimer/ and
/home/ appeared beside it -- and six test files had the old location written
into them as a string. Two used os.path.join("docs", "app", ...) rather than
the literal "docs/app", so a project-wide search for the old path found four
of the six and the suite went red on the ones it missed.

One definition here, imported everywhere. The next move is a one-line edit.
"""

import os
import sys

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, REPO)

DOCS = os.path.join(REPO, "docs")

# The three published pages.
DISCLAIMER_HTML = os.path.join(DOCS, "disclaimer", "index.html")
HOME_HTML = os.path.join(DOCS, "home", "index.html")
FORM_HTML = os.path.join(DOCS, "form", "index.html")

# The browser build: generated by tools/build_web.py, never hand-edited.
FORM_DIR = os.path.join(DOCS, "form")
FORM_PY = os.path.join(FORM_DIR, "py")

BASE_CSS = os.path.join(DOCS, "assets", "base.css")

# Relative to docs/, for anything serving the directory over HTTP.
PAGES_REL = {
    "disclaimer": "disclaimer/index.html",
    "home": "home/index.html",
    "form": "form/index.html",
}


def read(path):
    with open(path, encoding="utf-8") as fh:
        return fh.read()
