"""
What is safe to publish.

This repository is public, it is built around other people's medical
records, and the working files the tool produces during a real run sit in
the same directory as the source. The gap between those two facts is one
`git add -A` wide.

PHI has leaked into this project's output twice during development -- both
times into debug printing, both times caught by eye. Eyes do not scale and
they do not run on a fork. These tests are the thing that does.

They check what is COMMITTED, not what is on disk: a working copy full of
real records is fine and expected, and .gitignore is what keeps it that way.
"""

import hashlib
import os
import re
import subprocess
import sys

import pytest

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, REPO)

BINARY = (".pdf", ".png", ".jpg", ".jpeg", ".gif", ".docx", ".zip", ".ico")

# Synthetic identities the fixtures are allowed to use. Anything matching a
# name shape outside this list is assumed real until a human says otherwise.
FAKE_SURNAMES = {
    "DEMO", "DOE", "EXAMPLE", "FICTION", "SAMPLE", "TESTCASE", "ROE",
    "PLACEHOLDER", "PATIENT", "TEST",
}

# Placeholder identifiers. 123-45-6789 is the canonical invalid example SSN.
ALLOWED_IDS = {"123-45-6789", "XXX-XX-0000", "0000000000", "1234567890"}


def tracked_files():
    out = subprocess.run(["git", "ls-files", "-z"], cwd=REPO,
                         capture_output=True, text=True, check=True)
    return [f for f in out.stdout.split("\0") if f]


def text_files():
    for rel in tracked_files():
        if rel.lower().endswith(BINARY):
            continue
        path = os.path.join(REPO, rel)
        if not os.path.exists(path):
            continue
        try:
            with open(path, encoding="utf-8") as fh:
                yield rel, fh.read()
        except (UnicodeDecodeError, IsADirectoryError):
            continue


# ------------------------------------------------------------ identifiers

def test_no_committed_file_contains_a_social_security_number():
    pattern = re.compile(r"\b\d{3}-\d{2}-\d{4}\b")
    bad = []
    for rel, text in text_files():
        for hit in pattern.findall(text):
            if hit not in ALLOWED_IDS:
                bad.append(f"{rel}: {hit}")
    assert not bad, "SSN-shaped strings committed: " + "; ".join(bad)


def test_no_committed_file_contains_a_dod_id():
    """EDIPI is ten digits. Bare ten-digit runs are rare enough in source
    that flagging them all and allowlisting the placeholders is cheaper
    than being clever."""
    pattern = re.compile(r"(?<![\d.-])\d{10}(?![\d.-])")
    bad = []
    for rel, text in text_files():
        if rel.endswith(".json") and "crosswalk" in rel:
            continue  # form field geometry, not identifiers
        for hit in pattern.findall(text):
            if hit not in ALLOWED_IDS:
                bad.append(f"{rel}: {hit}")
    assert not bad, "DoD-ID-shaped strings committed: " + "; ".join(bad)


def test_no_committed_file_names_a_real_clinician():
    """MHS Genesis writes providers as LAST, FIRST M, CREDENTIAL. Real ones
    reached a code comment and three commit messages during development."""
    pattern = re.compile(
        r"\b([A-Z][A-Z]{2,}),\s+[A-Z][A-Z]+(?:\s+[A-Z])?,\s+"
        r"(?:MD|DO|NP|PA|RN|PHD|LCSW|DDS|PsyD)\b")
    bad = []
    for rel, text in text_files():
        for surname in pattern.findall(text):
            if surname not in FAKE_SURNAMES:
                bad.append(f"{rel}: {surname}")
    assert not bad, (
        "possible real clinician names committed: " + "; ".join(bad)
        + " — add to FAKE_SURNAMES only if the name is invented")


# ------------------------------------------------------ the working files

@pytest.mark.parametrize("artifact", [
    "conditions.json",
    "conditions_worksheet.md",
    "proposals.json",
    "ocr_output.json",
    "reconciliation.json",
    "mhs_genesis.txt",
    "pii_literals.txt",
])
def test_run_artifacts_are_never_committed(artifact):
    """These are produced by processing a real record. Each has existed in
    the working copy of this repo."""
    assert artifact not in tracked_files(), (
        f"{artifact} is committed and contains real extraction output")


def test_gitignore_still_covers_the_artifacts():
    """A test that only checks the current tracked list passes right up
    until somebody deletes a gitignore line and runs `git add -A`."""
    ignored = subprocess.run(
        ["git", "check-ignore", "-q", "conditions.json"],
        cwd=REPO).returncode == 0
    assert ignored, "conditions.json is no longer gitignored"


# The one PDF outside forms/ that belongs in the repo: the synthetic record
# the test suite runs against, generated by tools/make_sample_record.py from
# invented names and invented diagnoses. Its CONTENT is scanned below like
# any other file, so allowing it by path does not exempt it from review.
ALLOWED_NON_FORM_PDFS = {"tools/sample_record.pdf"}


def test_no_pdf_is_committed_except_the_blank_forms_and_the_sample():
    for rel in tracked_files():
        if not rel.lower().endswith(".pdf"):
            continue
        if rel in ALLOWED_NON_FORM_PDFS:
            continue
        assert "/forms/" in rel or rel.startswith("forms/"), (
            f"{rel} is a committed PDF outside forms/ — records must never "
            "be committed")


def pdf_text(rel):
    from pypdf import PdfReader
    reader = PdfReader(os.path.join(REPO, rel))
    return "\n".join((page.extract_text() or "") for page in reader.pages)


@pytest.mark.parametrize("rel", sorted(ALLOWED_NON_FORM_PDFS))
def test_the_committed_sample_record_contains_no_real_identity(rel):
    """Every text scan above skips PDFs, so a real record committed by
    accident would pass all of them. This reads the one PDF that is allowed
    to carry content and holds it to the same standard."""
    if rel not in tracked_files():
        pytest.skip(f"{rel} is not committed")
    text = pdf_text(rel)

    for hit in re.findall(r"\b\d{3}-\d{2}-\d{4}\b", text):
        assert hit in ALLOWED_IDS, f"{rel} contains an SSN: {hit}"

    names = re.findall(
        r"\b([A-Z][A-Z]{2,}),\s+[A-Z][A-Z]+(?:\s+[A-Z])?,\s+"
        r"(?:MD|DO|NP|PA|RN|PHD|LCSW|DDS|PsyD)\b", text)
    unknown = {n for n in names if n not in FAKE_SURNAMES}
    assert not unknown, f"{rel} names possibly-real clinicians: {unknown}"


# "Unset" has three spellings in these forms. /Off is the usual one; a bare
# "/" is an empty name object, which is how VA's blank SHA ships 131 of its
# radio groups -- present in the government original, not something this
# repo introduced. Treating "/" as a value made this test claim the blank
# form was filled.
UNSET = (None, "", "/", "/Off")


def test_the_committed_forms_are_actually_blank():
    """If a filled copy were ever committed over a blank one, every field
    would carry a real answer and every generated package would inherit it."""
    from pypdf import PdfReader
    checked = 0
    for rel in tracked_files():
        if not rel.lower().endswith(".pdf") or rel in ALLOWED_NON_FORM_PDFS:
            continue
        fields = PdfReader(os.path.join(REPO, rel)).get_fields() or {}
        filled = {k: v.get("/V") for k, v in fields.items()
                  if v.get("/V") not in UNSET}
        assert not filled, f"{rel} has {len(filled)} filled fields: {list(filled)[:5]}"
        checked += 1
    assert checked, "no forms were checked — the glob is wrong"


# ----------------------------------------------------- the shipped forms

def form_digest(rel):
    with open(os.path.join(REPO, rel), "rb") as fh:
        return hashlib.sha256(fh.read()).hexdigest()[:16]


def test_the_vendored_forms_have_not_silently_changed():
    """Field names are the contract between this tool and the PDFs. A form
    revision renames them, and every mapping in field_map.py and intake.py
    starts writing to fields that no longer exist -- or worse, to fields
    that do exist and mean something else.

    This fails when a form file changes. That is the point: a new edition
    is a deliberate re-verification, not something that arrives with a
    `git pull`.
    """
    pinned = os.path.join(REPO, "forms", "FORM_VERSIONS.txt")
    assert os.path.exists(pinned), (
        "forms/FORM_VERSIONS.txt is missing — run tools/pin_forms.py")

    expected = {}
    for line in open(pinned, encoding="utf-8"):
        line = line.strip()
        if line and not line.startswith("#"):
            digest, rel = line.split(None, 1)
            expected[rel] = digest

    for rel, digest in expected.items():
        assert os.path.exists(os.path.join(REPO, rel)), f"{rel} is gone"
        actual = form_digest(rel)
        assert actual == digest, (
            f"{rel} changed ({digest} -> {actual}).\n"
            "If this is a new edition of the form: re-run "
            "tools/inspect_fields.py, confirm every field name in "
            "field_map.py and intake.py still exists, then re-pin with "
            "tools/pin_forms.py.")
