#!/usr/bin/env python3
"""
tools/pin_forms.py — record which edition of each form this tool targets.

Field names are the contract between this tool and the PDFs it fills. A
form revision renames them, and every mapping starts writing to fields
that no longer exist -- or, worse, to fields that do exist and now mean
something else. Neither failure is loud on its own.

Pinning the file hashes makes a new edition a deliberate act: the test
fails, somebody re-checks the field names, and only then re-pins.

    python tools/pin_forms.py
"""

import hashlib
import os

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
FORMS = os.path.join(REPO, "forms")
OUT = os.path.join(FORMS, "FORM_VERSIONS.txt")

HEADER = """\
# Which edition of each form this tool targets.
#
# Generated by tools/pin_forms.py. Regenerating is a deliberate act: a
# changed hash means the PDF changed, which means the AcroForm field names
# may have changed, which means field_map.py and intake.py may be writing
# to fields that no longer exist. Before re-pinning:
#
#   1. python tools/inspect_fields.py <form.pdf>
#   2. confirm every field named in field_map.py and intake.py is present
#   3. run the tests
#   4. only then re-run this script
#
# sha256[:16]      path
"""


def main():
    lines = []
    for name in sorted(os.listdir(FORMS)):
        if not name.lower().endswith(".pdf"):
            continue
        rel = f"forms/{name}"
        with open(os.path.join(REPO, rel), "rb") as fh:
            digest = hashlib.sha256(fh.read()).hexdigest()[:16]
        lines.append(f"{digest}  {rel}")
        print(f"  {digest}  {rel}")

    with open(OUT, "w", encoding="utf-8") as fh:
        fh.write(HEADER + "\n".join(lines) + "\n")
    print(f"\npinned {len(lines)} form(s) -> forms/FORM_VERSIONS.txt")


if __name__ == "__main__":
    main()
